theme: minima
title: COOL BLOG
author: COOL DUDE
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome to my COOL site- ayone who enters is really cool and swag :)

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
